# Quick Test Config - Local Example Images
# ==========================================
# For testing the pipeline before full S3 training
# Uses /home/shadeform/example_images (10 fields, 80 images)
# Runs 50 iterations to verify everything works

MODEL:
  META_ARCHITECTURE: SSLMetaArch
  DEVICE: cuda
  WEIGHTS: ''
  DTYPE: float32

compute_precision:
  param_dtype: bf16
  reduce_dtype: fp32
  sharding_strategy: SHARD_GRAD_OP

dino:
  loss_weight: 1.0
  global_ignore_diagonal: true
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_norm_last_layer: false
  head_nlayers: 3
  head_hidden_dim: 2048
  koleo_loss_weight: 0.1
  koleo_loss_distributed: false
  koleo_topk: 1
  koleo_distributed_replicas: 0
  koleo_distributed_loss_group_size: null
  koleo_distributed_loss_group_data: true
  force_weight_norm: false
  reweight_dino_local_loss: false

ibot:
  loss_weight: 1.0
  mask_sample_probability: 0.5
  mask_ratio_min_max:
    - 0.1
    - 0.5
  mask_random_circular_shift: false
  force_masking_even_with_zero_weight: false
  separate_head: true
  head_n_prototypes: 65536
  head_bottleneck_dim: 256
  head_norm_last_layer: false
  head_nlayers: 3
  head_hidden_dim: 2048

gram:
  use_loss: false
  compute_stats: false

# Training configuration - LOCAL TEST
train:
  batch_size_per_gpu: 2  # Small batch for quick test
  dataset_path: JUMPSimpleLocal:root=/home/shadeform/example_images
  output_dir: /home/shadeform/DINOCell/training/ssl_pretraining/test_output
  saveckp_freq: 20
  seed: 42
  num_workers: 2  # Fewer workers for test
  OFFICIAL_EPOCH_LENGTH: 10  # Short epochs for test
  monitor_gradient_norm: false
  chunk_schedule: []
  cache_dataset: false
  use_teacher_head: true
  learn_from_teacher_tokens: false
  centering: sinkhorn_knopp
  checkpointing: false
  compile: false  # Disable compilation for faster startup
  cudagraphs: false
  use_multichannel_augmentation: true  # Multi-view mode

student:
  arch: vit_small
  patch_size: 8
  drop_path_rate: 0.1
  layerscale: 1.0e-05
  pretrained_weights: '../../dinov3_modified/dinov3/checkpoints/dinov3_vits16_pretrain_lvd1689m-08c60483.pth'
  ffn_layer: mlp
  ffn_ratio: 4.0
  resume_from_teacher_chkpt: ''
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  norm_layer: layernorm
  n_storage_tokens: 4
  mask_k_bias: true
  in_chans: 3
  pos_embed_type: rope
  pos_embed_rope_base: 100.0

teacher:
  momentum_teacher: 0.996
  final_momentum_teacher: 1.0
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_epochs: 10
  in_chans: 3

distillation:
  enabled: false

multidistillation:
  enabled: false

hrft:
  enabled: false

optim:
  epochs: 5  # Just 5 epochs for quick test (50 iterations total)
  optimizer: adamw
  weight_decay: 0.04
  weight_decay_end: 0.2
  lr: 5.0e-5
  warmup_epochs: 1  # Short warmup for test
  min_lr: 1.0e-06
  schedule_trunc_extra: 0.0
  clip_grad: 3.0
  freeze_last_layer_epochs: 1
  scaling_rule: sqrt_wrt_1024
  patch_embed_lr_mult: 0.2
  dino_head_wd_multiplier: 1.0
  layerwise_decay: 0.9
  multi_tensor_optim: true
  dump_fsdp_weights_path: ''
  adamw_beta1: 0.9
  adamw_beta2: 0.999

crops:
  global_crops_scale:
    - 0.4
    - 1.0
  local_crops_number: 8
  local_crops_scale:
    - 0.05
    - 0.4
  global_crops_size: 224
  local_crops_size: 96
  global_local_crop_pairs_ratios: 1.0
  gram_teacher_crops_size: null
  localcrops_subset_of_globalcrops: false
  share_color_jitter: false
  horizontal_flips: true
  gram_teacher_no_distortions: false
  num_channels: 5
  channel_selection_mode: random
  rgb_mean:
    - 0.485
    - 0.456
    - 0.406
  rgb_std:
    - 0.229
    - 0.224
    - 0.225

# Wandb logging configuration - TEST MODE
wandb:
  enabled: true
  project: dinocell-test  # Separate project for tests
  name: test_local_images
  entity: null
  log_interval: 5  # Log frequently for test
  log_attention_maps: true  # Test attention logging
  attention_log_interval: 10  # Log attention frequently for test
  save_checkpoints_to_wandb: false

evaluation:
  eval_period_iterations: 25  # Quick eval for test
  low_freq_every: 1
  config_files:
    high_freq: benchmark_high_frequency.yaml
    low_freq: benchmark_low_frequency.yaml

checkpointing:
  period: 25  # Save checkpoint at iteration 25
  max_to_keep: 2
  keep_every: 99999999999999999

